# Generated by Django 3.1.7 on 2021-03-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_on',
            new_name='createdTimestamp',
        ),
        migrations.AddField(
            model_name='post',
            name='lastUpdatedTimestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
