# Generated by Django 3.1.7 on 2021-03-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210313_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
