# Generated by Django 3.1.7 on 2021-03-14 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210314_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='createdTimestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
