# Generated by Django 3.1.7 on 2021-03-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_image_createdtimestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='default.jpg', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(default='default.com', max_length=300),
            preserve_default=False,
        ),
    ]
