# Generated by Django 3.1.7 on 2021-03-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210315_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(default='default.com', max_length=300),
            preserve_default=False,
        ),
    ]
