# Generated by Django 3.1.7 on 2021-03-15 02:21

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210315_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to=api.models.get_image_upload_path),
            preserve_default=False,
        ),
    ]
