# Generated by Django 3.1.7 on 2021-03-25 02:41

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPost',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='audio_post', serialize=False, to='api.post')),
                ('video', models.FileField(upload_to=api.models.get_audio_upload_path)),
            ],
            options={
                'db_table': 'audioPost',
            },
        ),
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='video_post', serialize=False, to='api.post')),
                ('video', models.FileField(upload_to=api.models.get_video_upload_path)),
            ],
            options={
                'db_table': 'videoPost',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='api.category'),
        ),
    ]
