# Generated by Django 3.1.7 on 2021-03-25 02:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210325_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopost',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.FileField(null=True, upload_to=api.models.get_audio_upload_path),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(null=True, upload_to=api.models.get_video_upload_path),
        ),
        migrations.DeleteModel(
            name='AudioPost',
        ),
        migrations.DeleteModel(
            name='VideoPost',
        ),
    ]
